import { NextRequest, NextResponse } from 'next/server';
import { resolveContext } from '@/lib/supabase/sim';

/**
 * POST /api/sim/save-card
 *
 * Saves a rewire card to sim_rewire_cards.
 * Called by ToneyContext's handleSaveCard/handleSaveInsight in sim mode
 * (replaces direct Supabase client writes that can't access sim_ tables).
 *
 * Body: { title, content, category, sessionId?, sourceMessageId?, triggerContext?, autoGenerated? }
 */
export async function POST(request: NextRequest) {
  try {
    const ctx = await resolveContext(request);
    if (!ctx || !ctx.isSimMode) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { title, content, category, sessionId, sourceMessageId, triggerContext, autoGenerated } = await request.json();

    if (!content?.trim()) {
      return NextResponse.json({ error: 'Missing content' }, { status: 400 });
    }

    const { data, error } = await ctx.supabase
      .from(ctx.table('rewire_cards'))
      .insert({
        user_id: ctx.userId,
        title: title || content.substring(0, 80),
        content: content.trim(),
        category: category || 'reframe',
        session_id: sessionId || null,
        source_message_id: sourceMessageId || null,
        trigger_context: triggerContext || null,
        auto_generated: autoGenerated || false,
      })
      .select('id')
      .single();

    if (error) {
      console.error('Sim save-card error:', error);
      return NextResponse.json({ error: 'Failed to save card' }, { status: 500 });
    }

    return NextResponse.json({ id: data?.id || null });
  } catch (error) {
    console.error('Sim save-card error:', error);
    return NextResponse.json({ error: 'Failed to save card' }, { status: 500 });
  }
}
