-- Add understanding snippet column for home screen "What Toney sees" tile
-- One evolving sentence generated by evolveUnderstanding / seedUnderstanding

ALTER TABLE profiles ADD COLUMN understanding_snippet TEXT;
ALTER TABLE sim_profiles ADD COLUMN understanding_snippet TEXT;
